apiVersion: shardingsphere.sphere-ex.com/v1alpha1
kind: ProxyConfig
metadata:
  name: proxyconfig-usertest
spec:
  authority:
    users:
      - user: root@%
        password: root
      - user: sphere@%
        password: sphere
    privilege:
      type: ALL_PRIVILEGES_PERMITTED
  mode:
    type: Cluster
    repository:
      type: ZooKeeper
      props:
        namespace: "governance_ds"
        server-lists: "zookeeper.default:2181"
        retryIntervalMilliseconds: 500
        timeToLiveSeconds: 600
        maxRetries: 3
        operationTimeoutMilliseconds: 5000
    overwrite: false