# permissions for end users to edit proxyconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxyconfig-editor-role
rules:
- apiGroups:
  - sphere-ex.com.sphere-ex.com
  resources:
  - proxyconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sphere-ex.com.sphere-ex.com
  resources:
  - proxyconfigs/status
  verbs:
  - get
