---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: proxyconfigs.shardingsphere.sphere-ex.com
spec:
  group: shardingsphere.sphere-ex.com
  names:
    kind: ProxyConfig
    listKind: ProxyConfigList
    plural: proxyconfigs
    singular: proxyconfig
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.metadataRepository
      name: MetadataRepository
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ProxyConfig is the Schema for the proxyconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ProxyConfigSpec defines the desired state of ProxyConfig
            properties:
              authority:
                description: Auth  is used to set up initial user to login compute
                  node, and authority data of storage node.
                properties:
                  privilege:
                    description: Privilege for storage node, the default value is
                      ALL_PRIVILEGES_PERMITTED
                    properties:
                      type:
                        type: string
                    required:
                    - type
                    type: object
                  users:
                    items:
                      description: 'User is a slice about authorized host and password
                        for compute node. Format: user:<username>@<hostname>,hostname
                        is % or empty string means do not care about authorized host
                        password:<password>'
                      properties:
                        password:
                          type: string
                        user:
                          type: string
                      required:
                      - password
                      - user
                      type: object
                    type: array
                required:
                - users
                type: object
              mode:
                description: ClusterConfig needs to fill in the relevant configuration
                  required by Cluster mode
                properties:
                  overwrite:
                    description: Whether overwrite persistent configuration with local
                      configuration
                    type: boolean
                  repository:
                    description: Persist repository configuration
                    properties:
                      props:
                        description: Properties of persist repository
                        properties:
                          digest:
                            description: Password of login
                            type: string
                          maxRetries:
                            description: 'MaxRetries Max retries of client connection.
                              default: 3'
                            type: integer
                          namespace:
                            description: Namespace of registry center
                            type: string
                          operationTimeoutMilliseconds:
                            description: 'OperationTimeoutMilliseconds Milliseconds
                              of operation timeout. default: 500'
                            type: integer
                          retryIntervalMilliseconds:
                            description: 'RetryIntervalMilliseconds Milliseconds of
                              retry interval. default: 500'
                            type: integer
                          server-lists:
                            description: Server lists of registry center
                            type: string
                          timeToLiveSeconds:
                            description: 'TimeToLiveSeconds Seconds of ephemeral data
                              live.default: 60'
                            type: integer
                        required:
                        - namespace
                        - server-lists
                        type: object
                      type:
                        description: Type of persist repository
                        enum:
                        - ZooKeeper
                        type: string
                    required:
                    - props
                    - type
                    type: object
                  type:
                    description: 'Type of mode configuration. Values only support:
                      Cluster'
                    enum:
                    - Cluster
                    type: string
                required:
                - overwrite
                - repository
                - type
                type: object
              props:
                description: 'Props TODO: description'
                properties:
                  check-duplicate-table-enabled:
                    type: boolean
                  check-table-metadata-enabled:
                    type: boolean
                  kernel-executor-size:
                    type: integer
                  proxy-backend-executor-suitable:
                    type: string
                  proxy-backend-query-fetch-size:
                    type: integer
                  proxy-frontend-executor-size:
                    type: integer
                type: object
            required:
            - authority
            - mode
            type: object
          status:
            description: ProxyConfigStatus defines the observed state of ProxyConfig
            properties:
              metadataRepository:
                type: string
            required:
            - metadataRepository
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
